---
title: The Year of the Thesis
author: Erin M. Buchanan
date: '2019-12-05'
slug: 2019-in-review
categories:
  - research
tags:
  - publication
subtitle: ''
---

The Year of the Thesis! 

Just wanted to highlight several publications from this year, which were mostly theses from some fabulous young researchers:

- Scofield, J.E., Kostic, B., & Buchanan, E.M. (2019). How the presence of others affects
desirability judgments in heterosexual and homosexual participants. Archives of Sexual Behavior, X, XX–XX. doi: 10.1007/s10508-019-01516-w 

- Maxwell, N.P. & Buchanan, E.M. (2019). Investigating the interaction of direct and indirect relation on memory judgments and retrieval. Cognitive Processing, X, XX–XX. doi:
10.1007/s10339-019-00935-w

- Knoph, R.E., & Buchanan, E.M. (2019). Language learning and metacognition: An intervention to improve second language classrooms. Journal of Scientific Psychology, X, XX–XX.

- Marshall, C.Z., Buchanan, E.M., & Fallone, M.D. (2019). Love, language, and linear algebra: Linguistic modeling of personality and mate preference. Modern Psychological Studies, X, XX–XX.

- Herr, D. & Buchanan, E.M. (2019). Generativity and other buffers of death awareness in first responders with PTSD. Anxiety, Stress, & Coping, X, XX–XX. doi: 10.1080/10615806.2019.1695522

Check out their work by going to the CV page - all documents are linked on that page. 